apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: tanzu-helm-resources
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: podinfo
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: "https://stefanprodan.github.io/podinfo"
    targetRevision: "6.9.0"
    chart: podinfo
    helm:
      values: |
        replicaCount: 1